- app/routes/login.js
Added a redirect for when the user is already logged in and tries to go to /login route
> KAS-1047 Fix login page redirects when logged in

- app/styles/_print.scss
Fixes https://kanselarij.atlassian.net/browse/KAS-973
> Fix an issue which causes Firefox to only print a single page

- app/controllers/application.js
Cherry picked the commit, because of development merge into the previous branch (this caused a lot of issues).
> Retrieve alerts in a way that hits the cache more often

- app/routes/application.js
Signed-off-by: Wolfr <johan.ronsse@gmail.com>
> Fix Chrome detection

- app/components/newsletter/newsletter-meeting/component.js
- app/services/newsletter-service.js
This got reverted by accident, this code should have stayed in development branch
> Kas 1091 new branch

- app/components/agenda/agenda-header/component.js
- app/services/file-service.js
- app/services/global-error.js
- translations/nl-be.json
> cherry-picked the file-bundling-service fix for KAS-1178

- app/components/agenda/agenda-decisions/template.hbs
- app/components/agenda/agenda-minutes/template.hbs
- app/components/agenda/agendaitem/agendaitem-decision/template.hbs
- app/components/news-item/edit-item/template.hbs
- app/styles/app.scss
- app/styles/custom-components/_vlc-agenda-items.scss
- app/styles/fixes/_fix-flex-utils.scss
- app/styles/govflanders/components/_modal.scss
Reverts kanselarij-vlaanderen/kaleidos-frontend#132
> Revert "KAS-1197"

- app/components/agenda/agendaitem/create-agendaitem/template.hbs
- app/components/utils/add-existing-document/template.hbs
Disable sorting (Data-tables does not allow it)
> KAS-1190: no sortable header for these templates

- app/components/utils/case-search/component.js
- app/components/utils/case-search/template.hbs
**WHAT CHANGED**
* Modal dialog was missing an important content class, that should sort out the height issues
* It also completely lacked a loading spinner, added that
* I also added some extra goodness around loading in general, so that it works properly. When searching for items, and when clicking on an item, improving feedback to the user.
> KAS-581: Height + loading fixes

- app/styles/app.scss
**OLD**
**NEW**
Just a small tweak!
> KAS-1215: Change environment pill

- app/components/agenda/agenda-header/template.hbs
- app/styles/custom-components/_vlc-page-header.scss
"Corporate needs you to find the difference between these two pictures":
Here's the link to the Figma artboard: https://www.figma.com/file/AMfVq1xYQ9jePVYy05IZJy/%F0%9F%92%AF-Kaleidos-Designs-Q1-2020-(Vlaanderen)?node-id=70%3A1301
> KAS-1217: Fix Agenda subtitle

- app/styles/app.scss
Reverts kanselarij-vlaanderen/kaleidos-frontend#194, should have been a merge to development first
> Revert "KAS-1215: Change environment pill"

- app/components/agendaitems/agendaitems-filter/template.hbs
- app/components/cases/cases-filter/template.hbs
- app/components/utils/search-legend/template.hbs
- app/styles/app.scss
- app/styles/custom-components/_vlc-search-legend.scss
- translations/nl-be.json
Added new custom popover component for search legend, and some accompanying custom styles.
> KAS-1169: Popover legend

- app/components/agenda/agendaitem/agendaitem-case/subcase-document/document-link/component.js
- app/components/agenda/agendaitem/agendaitem-case/subcase-document/document-link/template.hbs
- app/components/agenda/agendaitem/agendaitem-news-item/template.hbs
- app/components/agenda/agendaitem/create-agendaitem/component.js
- app/components/agenda/agendaitem/create-agendaitem/template.hbs
- app/components/ember-kaleidos-webuniversum/vl-uploaded-document/template.hbs
- app/components/news-item/edit-item/component.js
- app/components/news-item/edit-item/template.hbs
- app/components/subcases/subcases-overview-header/component.js
- app/components/subcases/subcases-overview-header/template.hbs
- app/components/web-components/vl-modal-verify/component.js
- app/controllers/cases/case/subcases/overview.js
- app/styles/custom-components/_vlc-agenda-items.scss
- app/templates/cases/case/subcases/overview.hbs
- cypress/integration/unit/cancel-editing-document.spec.js
- cypress/integration/unit/document-version.spec.js
- cypress/selectors/documents/documentSelectors.js
- cypress/support/document-commands.js
- package.json
- translations/nl-be.json
Pull request voor MTP-12-02-2020
> Mtp 12 02 2020

- app/styles/app.scss
This commit was reverted on master and the revert was merged into development
This will make a new commit so we get the changes back in the development branch
> Change look and feel of the environment pill

- app/components/access-level-pill/template.hbs
- app/models/access-level.js
Add priority to access-rights model and sort it in frontend
> KAS-1277: sorting access-rights in dropdown

- translations/nl-be.json
> KAS-1295: copy aanpassing

- app/components/agenda/agendaitem/agendaitem-decision-edit/component.js
- app/errors/modified-old-data-error.js
- app/mixins/edit-agendaitem-or-subcase.js
- app/models/model-with-modifier.js
- app/models/subcase.js
Deze PR kan niet zonder 
https://github.com/kanselarij-vlaanderen/kaleidos-project/pull/57
> KAS-1109: bubble up error for concurrency

- app/components/agenda/agenda-minutes/template.hbs
- app/components/agenda/agendaitem/agendaitem-case/subcase-mandatees/template.hbs
- app/components/utils/case-search/component.js
- app/components/utils/case-search/template.hbs
- app/components/web-components/vl-mandatee-link/template.hbs
- app/components/web-components/vl-modal-footer/component.js
- translations/nl-be.json
> Kas 1282 indiendende minister

- app/components/agenda/agenda-header/template.hbs
- app/styles/custom-components/_vlc-page-header.scss
> Add subtitle BEM child with sans-serif and normal font properties

- app/adapters/application.js
- app/components/agenda/agenda-list/list-item/template.hbs
- app/components/agenda/agendaitem/agendaitem-case/subcase-document/linked-document-link/component.js
- app/components/agenda/agendaitem/agendaitem-case/subcase-documents/component.js
- app/components/agenda/agendaitem/agendaitem-case/subcase-titles-edit/template.hbs
- app/components/agenda/agendaitem/agendaitem-decision-edit/component.js
- app/components/utils/add-existing-document/component.js
- app/components/utils/add-existing-document/template.hbs
- app/errors/modified-old-data-error.js
- app/mixins/edit-agendaitem-or-subcase.js
- app/models/agendaitem.js
- app/models/model-with-modifier.js
- app/models/model-with-toasts.js
- app/models/newsletter-info.js
- app/models/subcase.js
- app/services/global-error.js
- app/styles/custom-components/_vlc-agenda-items.scss
- translations/nl-be.json
> Mtp 05 03 2020
